### ISSUE TITLE
Add raw json text mode to chatbox api

### ISSUE THREAD

**Issue by scmcgowen** [SwitchCraftCC/issues#91] opened 2023-05-05 14:11 UTC
This would use Minecraft's raw json text like /tellraw uses.
It would be filtered to prevent operator commands from being ran by the chat message click event.
But you could have a click event to run a chatbox command or suggest a command or chatbox message.

**Comment by piprett** [comment] 2023-05-05 14:13
Duplicate of #45

**Closed as not planned** 2023-05-05 14:20 UTC
Labels: duplicate
